version: '3'
services:
  nginx:
    image: "nginx"
    volumes:
    - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
    - "8080:80"
  app:
    image: "bsenyshyn/hello-akka:latest"
    volumes:
    - /mysite.template
